apiVersion: v1
kind: Service
metadata:
  name: apisix-prometheus
  namespace: apisix
  labels:
    app.kubernetes.io/name: apisix
    app.kubernetes.io/instance: apisix
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: apisix
    app.kubernetes.io/instance: apisix
  ports:
  - name: prometheus
    port: 9091
    targetPort: 9091
